i'm tired boss

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -134,11 +134,18 @@ jobs:
           registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
+          
+      - name: 🧾 Show Dockerfile used
+        run: cat ./${{ matrix.folder }}/Dockerfile || echo "Dockerfile not found"
+
 
       - name: 🐳 Build and Push ${{ matrix.service }} Docker image
         run: |         
           docker build \
-            --no-cache \
-            -t ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}:latest ./${{ matrix.folder }}/Dockerfile
+          --no-cache \
+          -f ./${{ matrix.folder }}/Dockerfile \
+          -t ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}:latest \
+          ./${{ matrix.folder }}
+
           docker push ghcr.io/${{ github.repository_owner }}/${{ matrix.image_name }}:latest
 
